name: flutter_demo
description: Flutter Demo项目

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.3
  cached_network_image: ^3.2.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  date_picker_timeline: ^1.2.3 # 水平日期选择插件1
  device_preview: ^1.1.0
  dio: ^4.0.6
  easy_refresh: ^3.0.4+2
  flutter_date_picker_timeline: ^0.3.3 # 水平日期选择插件2
  flutter_easyloading: ^3.0.5  
  flutter_screenutil: ^5.3.1  
  image_cropper: ^3.0.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6
  jpush_flutter: 2.4.0
  mobile_scanner: ^2.0.0 # 二维码扫码插件2   
  path_provider: ^2.0.11  
  qr_code_scanner: ^1.0.1 # 二维码扫码插件1  
  qr_flutter: ^4.0.0
  responsive_framework: ^0.2.0  
  screenshot: ^1.2.3
  shared_preferences: ^2.0.1
  sqflite: ^2.0.3+1  
  url_strategy: ^0.2.0
  uuid: ^3.0.6  
  video_player: ^2.4.7
  web_socket_channel: ^2.2.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/